---
title: "Untitled"
author: "Claire Smith"
date: "2023-07-09"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r initialize, message=F}
# Load packages
library(tidyverse)
library(lme4) # for linear mixed effects models
library(lmerTest)
library(emmeans)
library(car)
library(knitr)
# Source files
source("clean-stig-01.R")
source("clean-stig-02.R")
source("theme_cs.R")
# Load data
stig <- read.csv("processed-data/stig-all.csv", stringsAsFactors = T)
stig$Date <- as.Date(stig$Date)
stig$Sex_sys <- as.factor(stig$Sex_sys)
stig$source <- as.factor(stig$source)
# summary(stig)
```

### Prepare data

```{r pre-processing data}
stigl <- stig %>% 
  mutate(Log_flw_pollen=log(Flw_pollen + 1)) %>% 
  rowwise %>% 
  mutate(Avg_dist = mean(c_across(c('D1', 'D2', 'D3', 'D4', 'D5')), na.rm=TRUE),
         Inv_avg_dist=1/Avg_dist) %>% 
  # Take only entries stigma length data
  filter(!is.na(Flw_pollen) & !is.na(Infl_max) & !is.na(Avg_dist) &!is.na(Stigma_length) & !is.na(Date))
# remove outlier identified in plots in anal-stig-full.Rmd...
# CAHI[which(CAHI$Stigma_length<1),] # small stigma has length 0.2 (most are between 2-3)
stigl2 <- stigl %>% filter(Species != "Carex hirtifolia" | 
                            (Species == "Carex hirtifolia" & Stigma_length>0.5))
```


```{r all stig length plots, fig.dim=c(14, 20), dpi=200}
stigl %>% 
  ggplot(aes(x=Stigma_length, y=Log_flw_pollen)) + 
  geom_point() + 
  geom_smooth(method="lm", se=F) + 
  facet_wrap(~Species, scales = "free", ncol=3) + 
  scale_y_continuous(name="Stigmatic pollen load",
                     breaks = log(c(0,1,2,5,10,25,50,100,200,500,1000, 2500)+1),
                     labels = c(0,1,2,5,10,25,50,100,200,500,1000, 2500)) +
  scale_x_continuous(name = "Stigma length (cm)") +
  theme_cs(font = "sans", fontsize=16) + 
  theme(strip.background = element_rect(linewidth = NULL,
                                        linetype = NULL,
                                        colour = "white"),
        strip.text = element_text(size = 14, face="italic"))
```

```{r all date plots, fig.dim=c(14,20), dpi=200}
stigl %>% 
  ggplot(aes(x=Date, y=Log_flw_pollen)) + 
  geom_point() + 
  geom_smooth(method="lm", se=F) + 
  facet_wrap(~Species, scales = "free", ncol=3) + 
  scale_y_continuous(name="Stigmatic pollen load",
                     breaks = log(c(0,1,2,5,10,25,50,100,200,500,1000, 2500)+1),
                     labels = c(0,1,2,5,10,25,50,100,200,500,1000, 2500)) +
  scale_x_date(name = "Date")+ 
  theme_cs(font = "sans", fontsize=16) + 
  theme(strip.background = element_rect(linewidth = NULL,
                                        linetype = NULL,
                                        colour = "white"),
        strip.text = element_text(size = 14, face="italic"),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r all infl max plots, fig.dim=c(14, 20), dpi=200}
stigl %>% 
  ggplot(aes(x=Infl_max, y=Log_flw_pollen)) + 
  geom_point() + 
  geom_smooth(method="lm", se=F) + 
  facet_wrap(~Species, scales = "free", ncol=3) + 
  scale_y_continuous(name="Stigmatic pollen load",
                     breaks = log(c(0,1,2,5,10,25,50,100,200,500,1000, 2500)+1),
                     labels = c(0,1,2,5,10,25,50,100,200,500,1000, 2500)) +
  scale_x_continuous(name = "Max plant height (cm)")+ 
  theme_cs(font = "sans", fontsize=16) + 
  theme(strip.background = element_rect(linewidth = NULL,
                                        linetype = NULL,
                                        colour = "white"),
        strip.text = element_text(size = 14, face="italic"))
```

```{r all inv avg dist plots, fig.dim=c(14,20), dpi=200}
stigl %>% 
  ggplot(aes(x=Inv_avg_dist, y=Log_flw_pollen)) + 
  geom_point() + 
  geom_smooth(method="lm", se=F) + 
  facet_wrap(~Species, scales = "free", ncol=3) + 
  scale_y_continuous(name="Stigmatic pollen load",
                     breaks = log(c(0,1,2,5,10,25,50,100,200,500,1000, 2500)+1),
                     labels = c(0,1,2,5,10,25,50,100,200,500,1000, 2500)) +
  scale_x_continuous(name = "Inverse average distance to nearest pollen-producing neighbour (1/cm)")+ 
  theme_cs(font = "sans", fontsize=16) + 
  theme(strip.background = element_rect(linewidth = NULL,
                                        linetype = NULL,
                                        colour = "white"),
        strip.text = element_text(size = 14, face="italic"))
```

```{r}
# stigl %>% 
#   filter(Species=="Rumex acetosella") %>% 
#   ggplot(aes(x=Avg_dist, y=Flw_pollen)) + 
#   geom_point() + 
#   geom_smooth(method="lm", se=F, formula = log(y+1) ~ 1/x) + 
#   facet_wrap(~Species, scales = "free", ncol=3) + 
#   # scale_y_continuous(name="Stigmatic pollen load",
#   #                    breaks = log(c(0,1,2,5,10,25,50,100,200,500,1000, 2500)+1),
#   #                    labels = c(0,1,2,5,10,25,50,100,200,500,1000, 2500)) +
#   scale_x_continuous(name = "Inverse average distance to nearest pollen-producing neighbour (1/cm)")+ 
#   theme_cs(font = "sans", fontsize=16) + 
#   theme(strip.background = element_rect(linewidth = NULL,
#                                         linetype = NULL,
#                                         colour = "white"),
#         strip.text = element_text(size = 14, face="italic"))
```

Run models all at once to get coefficient summaries easily: 

```{r}
#nest data by species to make it easier to handle
by_spp <- stigl %>% group_by(Species, Sex_sys) %>% 
  nest() %>% 
  arrange(Sex_sys, Species)
```

Now I'll run linear models predicting pollen production by pollen size, and pull out the ones with a significant relationship. 

```{r, linear regression models}
# , cols.print=14
library(broom.mixed)
#define function to run model 
spp_model <- function(df) {
  lmer(Log_flw_pollen ~ Infl_max + Stigma_length + Date + Inv_avg_dist + (1|Plant), data=df)
}

#run models and add model to by_spp dataframe
by_spp <- by_spp %>% 
  mutate(model = purrr::map(data, spp_model)) %>% 
  arrange(Sex_sys, Species) # arrange in order of sex sys, then alphabetical
#get model summary using glance() from "broom"
glance <- by_spp %>% 
  mutate(glance = purrr::map(model, broom.mixed::glance)) %>% #need to use broom.mixed::glance for mixed model
  unnest(glance)
# put this in a viewable format (remove nested data and model info)
glancetab <- glance %>% select(-c(data, model)) %>% 
  arrange(Sex_sys, Species)

#save this in a new table without the ugly list elements, which I can print to a file
glancetab_write <- glance %>% select(-c(data, model)) %>% 
  arrange(Sex_sys, Species) %>% apply(2, as.character) # coercing all columns to characters so that I can write this to a file
write.csv(glancetab_write, "processed-data/stigfull-reg-model-sum.csv", row.names = F)
#take a look
# print(glancetab, n=Inf)

#similar - but using broom::tidy(), gives me model coefficients
tidy <- by_spp %>% 
  mutate(tidy = purrr::map(model, broom.mixed::tidy, effects="fixed")) %>% 
  unnest(tidy)
tidytab <- tidy %>% select(-c(data, model)) %>% 
  arrange(Sex_sys, Species)
print(tidytab, n=46)
tidytab_write <- tidy %>% select(-c(data, model)) %>% 
  arrange(Sex_sys, Species) 
# %>% apply(2, as.character)
write.csv(tidytab_write, "processed-data/stigfull-reg-model-coefs.csv", row.names = F)
#take a look
# print(tidytab, n=Inf)


```