---
title: "Pollen production summary"
author: "Claire Smith"
date: "2023-06-26"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r initialize, message=F}
## Load packages
library(tidyverse)
library(ggplot2)
library(ggridges)

## Source files
# custom
source("theme_cs.R")
# data cleaning
source("clean-anthers-04.R") # calls 1, 2, 3 within itself
```

```{r}
# Pollen production (and size)
sizenum.dat <- read.csv("processed-data/size-prod-norep.csv", stringsAsFactors = T)
# Take data with no reps between JF and CS data
# head(sizenum.dat)
# str(sizenum.dat)
```

```{r prepare data}
prod_spp <- sizenum.dat

prod_spp <- prod_spp %>% 
  # Update species names
  # Agropyron trachycaulum => Elymus trachycaulus
  # Elymus innovatus => Leymus innovatus
  mutate(Species = gsub("Agropyron trachycaulum", "Elymus trachycaulus", Species),
         Species = gsub("Elymus innovatus", "Leymus innovatus", Species)) %>% 
  mutate(Species = gsub("Bcarianatus", "Bromus carinatus", Species),
         Species = gsub("Astolonifera", "Agrostis stolonifera", Species)) 


# Re-order levels in sex system column 
prod_spp$Sex_sys <- as.character(prod_spp$Sex_sys)
prod_spp$Sex_sys <- factor(prod_spp$Sex_sys, levels=c("dioecious", "monoecious", "hermaphroditic"))

# Arrange data so that species are grouped by sex system and ordered alphabetically
prod_spp <- arrange(prod_spp, Sex_sys, Species)
prod_spp$Species <- factor(prod_spp$Species, levels = unique(prod_spp$Species), ordered = T)

# Remove NAs
prod_spp <- prod_spp %>% 
  filter(!is.na(Avg_pol_anth))

# Keep only species with at least 3 individuals
p_sum <- prod_spp %>% group_by(Species) %>% dplyr::summarize(n=n())
keep_vec <- p_sum$Species[which(p_sum$n>=3)]
p_all_3ormore <- prod_spp[prod_spp$Species %in% keep_vec,]

prodfull <- p_all_3ormore %>% droplevels() 

# Version with at least 5 indiviuals per species
keep_vec2 <- p_sum$Species[which(p_sum$n>=5)]
prodfilt <- prodfull[prodfull$Species %in% keep_vec2,] 
prodfilt <- prodfilt %>% droplevels()

```

```{r}
prod_sum <- prodfull %>% 
  group_by(Species, Sex_sys, source) %>% 
  summarize(Avg_prod_anth_sp = mean(Avg_pol_anth, na.rm=T),
            Sd_prod_anth_sp = sd(Avg_pol_anth, na.rm=T),
            n_prod_anth = n(),
            SE_prod_anth_sp = Sd_prod_anth_sp/n_prod_anth, 
            Max_prod_anth = max(Avg_pol_anth, na.rm=T),
            Min_prod_anth = min(Avg_pol_anth, na.rm=T),
            CV_prod_anth = Sd_prod_anth_sp/Avg_prod_anth_sp) %>% 
  droplevels()
print(prod_sum, n=Inf)
# write it to a file
write.csv(prod_sum, "summary-data/pollen-prod-table.csv", row.names=F)

```

```{r plot prod distributions, fig.dim=c(14,10), dpi=200}
prod_ridges <- prodfilt %>% 
  # Arrange species in order of sex system and alphabetically by species
  mutate(Sex_sys = as.character(Sex_sys),
         Sex_sys = factor(Sex_sys, levels=c("dioecious", "monoecious", "hermaphroditic")) ) %>% 
  arrange(desc(Sex_sys), desc(Species)) %>% 
  mutate(Species =  factor(Species, levels = unique(Species), ordered = T)) %>% 
  
  ggplot(aes(x=Avg_pol_anth, y=Species, fill=Sex_sys)) +
  geom_density_ridges2() + 
  scale_fill_manual(values=c("#66C2A5","#8DA0CB","#FC8D62"),
                    labels=c("Dioecious", "Monoecious", "Hermaphroditic")) +
  scale_x_continuous(name = "Pollen per anther") + 

  scale_y_discrete() +
  ylab(label="") + 
  guides(fill="none") + 
  theme_cs(font="sans", fontsize=15) + 
  theme(axis.text.y = element_text(face = "italic"),
        axis.ticks.y = element_line())

prod_ridges
```


```{r prod boxplots, fig.dim=c(14,10), dpi=200}
prod_box <- prodfull_filt %>% 
    # Arrange species in order of sex system and alphabetically by species
  mutate(Sex_sys = as.character(Sex_sys),
         Sex_sys = factor(Sex_sys, levels=c("dioecious", "monoecious", "hermaphroditic")) ) %>% 
  arrange(Sex_sys, Species) %>% 
  mutate(Species =  factor(Species, levels = unique(Species), ordered = T)) %>% 
  
  ggplot() + 
  geom_boxplot(aes(x=Species, y=Avg_pol_anth, fill=Sex_sys)) + 

  scale_y_continuous(name = "Pollen per anther") + 
  scale_x_discrete(name = "") + 
  
  guides(fill="none") + 
  scale_fill_manual(labels=c("Dioecious", "Monoecious", "Hermaphroditic"),
                    values=c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme_cs(fontsize=15, font="sans") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, face="italic"))

prod_box
```


```{r sex sys prod box plots, fig.dim=c(8,8), dpi=200}
prod_box_ss <- prodfull_filt %>% 
  # Arrange species in order of sex system and alphabetically by species
  mutate(Sex_sys = as.character(Sex_sys),
         Sex_sys = factor(Sex_sys, levels=c("dioecious", "monoecious", "hermaphroditic")) ) %>% 
  arrange(Sex_sys, Species) %>% 
  mutate(Species =  factor(Species, levels = unique(Species), ordered = T)) %>% 
  
  ggplot() + 
  geom_boxplot(aes(x=Sex_sys, y=Avg_pol_anth, fill=Sex_sys),
               width=0.4) + 
  
  scale_y_continuous(name = "Pollen per anther") + 
  scale_x_discrete(name = "", labels = NULL) + 
  
  guides(fill=guide_legend(title="Sex system")) + 
  scale_fill_manual(labels=c("Dioecious", "Monoecious", "Hermaphroditic"),
                    values=c("#66C2A5","#8DA0CB","#FC8D62")) + 
  theme_cs(fontsize=15, font="sans") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "right")

prod_box_ss
```

