---
title: "Stigma length on pollen load"
author: "Claire Smith"
date: "2023-06-19"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r initialize, message=F}
# Load packages
library(tidyverse)
library(lme4) # for linear mixed effects models
library(lmerTest)
# Source files
source("clean-stig-01.R")
source("clean-stig-02.R")
source("theme_cs.R")
# Load data
stig <- read.csv("processed-data/stig-all.csv", stringsAsFactors = T)
```

```{r pre-processing data}
# Take only entries with infl height data and pollen load data
stigl <- stig %>% 
  filter(!is.na(Infl_max)&!is.na(Flw_pollen)&!is.na(Stigma_length))

# How many species have max infl height and stigma length? 
unique(stigl$Species) #  13 species 
# [1] Ambrosia artemisiifolia Chenopodium album       Carex communis          Carex hirtifolia       
#  [5] Carex pedunculata       Carex plantaginea       Carex stipata           Plantago lanceolata    
#  [9] Rumex acetosella        Rumex crispus           Scirpus microcarpus     Schizacne purpurascens 
# [13] Thalictrum dioicum
# View(stigl)

# Flower is nested within plant - each plant has (potentially) multiple flowers measured within it -- need to 
# create a unique plant ID for each plant within a species
stigl$Ind_ID=paste(stigl$Date, stigl$Site, stigl$Plant, sep = "-")
#How many unique individuals per species? 
stigl %>% group_by(Species) %>%
  distinct(Ind_ID) %>% 
  summarize(n=n())
#   Species                     n
#    <fct>                   <int>
#  1 Ambrosia artemisiifolia   118
#  2 Carex communis             81
#  3 Carex hirtifolia           89
#  4 Carex pedunculata          31
#  5 Carex plantaginea          38
#  6 Carex stipata             142
#  7 Chenopodium album          95
#  8 Plantago lanceolata       260
#  9 Rumex acetosella          201
# 10 Rumex crispus             108
# 11 Schizacne purpurascens    154
# 12 Scirpus microcarpus       137
# 13 Thalictrum dioicum         94

# I'll go through each species and run a model predicting pollen capture by flower height
# Since many likely have log-normal distributions of pollen capture, I'll create a log flw pollen variable now to # save time -- but will still check each species individually 
stigl$Log_flw_pollen <- log(stigl$Flw_pollen+1)
```

### Ambrosia artemisiifolia 

```{r pre-fit Ambrosia artemisiifolia}
dat <- stigl %>% 
  filter(Species=="Ambrosia artemisiifolia")
# summary(BRIN) 

#Taking a look at the data
hist(dat$Flw_pollen) # response variable. looks very right skewed!
hist(dat$Log_flw_pollen) # much more symmetric
hist(dat$Infl_max) # looks ok
```

```{r plant height vs pollen load Ambrosia artemisiifolia}
# Look at plot of Log_flw_pollen and Flw_height 
# Looks like no big differences between sites in flower height or pollen load
ggplot(data=dat, aes(x=Infl_max, y=Log_flw_pollen)) + 
  geom_point(size=3) + 
  scale_x_continuous(name="Plant height") + 
  scale_y_continuous(name="Log stigmatic pollen load") + 
  theme_cs()
ggplot(data=dat, aes(x=Stigma_length, y=Log_flw_pollen)) + 
  geom_point(size=3) + 
  scale_x_continuous(name="Stigma length") + 
  scale_y_continuous(name="Log stigmatic pollen load") + 
  geom_smooth(method="lm", se=F) + 
  theme_cs()
```

```{r stigma length vs pollen load Ambrosia artemisiifolia}
# Look at plot of Log_flw_pollen and Flw_height 
ggplot(data=dat, aes(x=Stigma_length, y=Log_flw_pollen)) + 
  geom_point(size=3) + 
  scale_x_continuous(name="Stigma length") + 
  scale_y_continuous(name="Log stigmatic pollen load") + 
  theme_cs()
```

```{r model fit }
#model for height
inflmax_mod <- lmer(Log_flw_pollen ~ poly(Infl_max, 2) + Stigma_length + (1|Ind_ID), data=dat)
summary(inflmax_mod)
anova(inflmax_mod)
# no sig quadratic or linear term for max height
stiglmod <- lmer(Log_flw_pollen ~ Stigma_length + (1|Ind_ID), data=dat)
summary(stiglmod)
anova(stiglmod)
# No significant effect of height on pollen loads in Bromus inermis.  
```

